export const ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    OAUTH: "/auth/oauth/google/app",
    CHECK_EMAIL: "/auth/checkEmail",
    FORGOT_PASSWORD: "/auth/requestReset",
  },
  USER: {
    GET_USER: "/users/profile",
    UPDATE_USER: "/users/update",
    UPDATE_WHEEL_CHAIR: "/users/wheelchair/update",
    FOLLOW_USER: "/users/follow",
  },
  LOCATION: {
    GET_LOCATIONS: "/location/findAllForMap",
    GET_LOCATION_SEARCH: "/location/admin/findAll",
    GET_LOCATION_DETAIL: "/location/findDetailByid",
    GET_LOCATION_FEATURES: "/location/findAllFeature",
    CALCULATE_LOCATION_FEATURES: "/location/calculateAccessibility",
  },
  REVIEW: {
    GET_REVIEWS: "/location/findReviewByLocationId",
    CREATE_REVIEW: "/location/locationReview",
    CREATE_REVIEW_FEATURES: "/location/featureLocationReview",
    GET_REVIEW_FEATURES: "/location/findFeature",
    GET_REVIEW_SUMMARY: "/location/findAvgReviewByLocationId",
    UPLOAD_REVIEW_IMAGE: "/location/featureLocationReviewImg",
    UPDATE_REVIEW: "/location/updateReview",
  },
  OBSTACLE: {
    CREATE_OBSTACLE: "/obstacle/insert",
    GET_OBSTACLES: "/obstacle/findAllForMap",
    GET_OBSTACLES_SEARCH: "/obstacle/admin/findAll",
    GET_OBSTACLE_DETAIL: "/obstacle/findById",
    GET_STATUS: "/obstacleStatus/findAll",
    GET_CATEGORIES: "/obstacleCategory/findAll",
    GET_SUBCATEGORIES: "/obstacleSubCategory/findByCategoryId",
    UPDATE_CONFIRMATION: "/obstacle/confirmation",
    CHECK_RESOLVE: "/obstacle/checkResolve",
  },
  ROUTE: {
    CREATE_ROUTE: "/recordedRoute/insert",
    GET_ROUTES: "/recordedRoute/findAllForMap",
    GET_ROUTES_SEARCH: "/recordedRoute/admin/findAll",
    GET_ROUTE_DETAIL: "/recordedRoute/findById",
    GET_ROUTES_BY_USER: "/recordedRoute/findRouteAllByUserId",
  },
  POST: {
    CREATE_POST: "/post/insert",
    LIKE_POST: "/post/like",
    COMMENT_POST: "/post/comment",
    UPDATE_POST: "/post/update",
    GET_POST_BOOKMARK: "/post/findPostBookmark",
    BOOKMARK_POST: "/post/insertPostBookmark",
    DELETE_BOOKMARK_POST: "/post/deletePostBookmark",
    GET_POSTS: "/post/findAll",
    GET_POST_CATEGORIES: "/postCategory/findAll",
    GET_POST_BY_ID: "/post/findById",
    GET_COMMENTS_BY_POST_ID: "/post/findComment",
    GET_POSTS_BY_USER: "/post/findAllPostByUserId",
    DELETE_POST: "/post/delete",
    UPDATE_COMMENT: "/post/updateComment",
  },
  SEARCH: {
    SEARCH: "/global/findAll",
  },
};
